services:
  codesniffer:
    image: php:7.4-cli-alpine3.16
    volumes:
      - ./:/var/pdga
    working_dir: /var/pdga

  composer:
    command: -V
    image: composer:2.4
    volumes:
      - ./:/var/pdga
    working_dir: /var/pdga
