services:
  codesniffer:
    image: php:8.2.4-cli-alpine
    volumes:
      - ./:/var/pdga
    working_dir: /var/pdga

  composer:
    command: -V
    image: composer:2.4
    volumes:
      - ./:/var/pdga
    working_dir: /var/pdga
